### ISSUE TITLE
Forbidden if I use: docker-compose-dev.yml

### ISSUE THREAD

**Issue by jujes** [alexcheng1982/docker-magento#11] opened 2016-07-23 12:51 UTC
![screen shot 2016-07-23 at 2 49 50 pm](https://cloud.githubusercontent.com/assets/2881017/17077949/ca4b6bde-50e4-11e6-9b92-cc39a538280d.png)

**Comment by sivajik34** [comment] 2016-09-26 06:41
I faced same issue only.@jujes issue resolved?

**Comment by nhammond101** [comment] 2016-09-26 12:52
i have the same issue, changing the dockerfile to install magento and sample data into _/var/www/html_ instead of _/var/www/htdocs_ seems to work
Nb. you'll also need to change the install-sampledata and install-magento scripts with the new path if required.

**Comment by alexcheng1982** [comment] 2016-09-28 10:44
Does this 403 error happen before of after installation? Cannot reproduce locally.

**Comment by alexcheng1982** [comment] 2016-09-30 00:50
See #14. Fixed in latest Docker Hub build.

**Closed as completed by alexcheng1982** 2016-09-30 00:50 UTC
